Add node class
kulla/mfnf-lua-scripts pull request #9
Opened 2016-09-14 12:08 UTC by vhaller

All recent changes merged to one pull request.

2016-09-14 12:45 UTC, kulla commented on src/Node.lua
> +  child.index  = #self.children
Why do you set the `index` attribute to the children's index? Is this attribute used somewhere?!

2016-09-14 12:48 UTC, kulla commented on test/Node_test.lua
> +node_2:add_child(node_3)
Use a `setUp()` function here (http://luaunit.readthedocs.io/en/latest/#grouping-tests-setup-teardown-functionality )

2016-09-14 12:55 UTC, kulla commented on test/Node_test.lua
> +  luaunit.assertTrue(getmetatable(root) == Node)
Use [assertIs](http://luaunit.readthedocs.io/en/latest/#assertIs):

    luaunit.assertIs(getmetatable(root), Node)

2016-09-14 12:56 UTC, kulla commented on test/Node_test.lua
> +  luaunit.assertNil(root.parent)
Missing:

    luaunit.assertItemsEquals(root.children, {})

See http://luaunit.readthedocs.io/en/latest/#assertItemsEquals

2016-09-14 12:58 UTC, kulla commented on test/Node_test.lua
> +  luaunit.assertTrue(#root.children == 2 and #node_2.children == 1)
Use `assertEquals` and write it in two lines...

2016-09-14 13:12 UTC, vhaller commented on src/Node.lua
> +  child.index  = #self.children
Right! I haven't noticed.

2016-09-14 13:14 UTC, kulla commented
@vhaller: Have a look on [how to format a git commit message](http://chris.beams.io/posts/git-commit/) :smile:

2016-09-14 13:18 UTC, kulla commented on test/Node_test.lua
> +  luaunit.assertTrue(root:find(function(node) return node == node_3 end) == node_3)
User [`assertIs`](http://luaunit.readthedocs.io/en/latest/#assertIs) here...

2016-09-14 14:39 UTC, kulla commented on test/Node_test.lua
> +  luaunit.assertFalse(node_1:last_child())
Use `assertIsNil` here...

2016-09-14 21:47 UTC, kulla commented on test/Node_test.lua
> +  luaunit.assertNil(root.parent)
`luaunit.assertItemsEquals(root.children, {})` is missing

2016-09-14 21:49 UTC, kulla commented on test/Node_test.lua
> +
Use a `setUp()` function here (http://luaunit.readthedocs.io/en/latest/#grouping-tests-setup-teardown-functionality )

2016-09-14 21:49 UTC, kulla commented on test/Node_test.lua
> +local root, node_1, node_2, node_3 = Node:new(), Node:new(), Node:new(), Node:new()
use variable names `node1`, `node2`, `node3`

2016-09-14 21:51 UTC, kulla commented on test/Node_test.lua
> +  luaunit.assertItemsEquals(root.children, {node_1, node_2})
Add

    luaunit.assertItemsEquals(node_1.children, {})
    luaunit.assertItemsEquals(node_2.children, { node_3 })
    luaunit.assertItemsEquals(node_3.children, {})

2016-09-14 21:52 UTC, kulla commented on test/Node_test.lua
> +  luaunit.assertIs(node_3.parent, node_2)
eine Leerzeile hier (ich weiß, dass ist ne ziemliche Kleinigkeit)... :smile:

2016-09-14 21:53 UTC, kulla commented on test/Node_test.lua
> +  luaunit.assertEquals(#node_2.children, 1)
Diese zwei Zeilen können gelöscht werden, da sie bereits durch

    luaunit.assertItemsEquals(root.children, {node_1, node_2})

abgedeckt werden...

2016-09-14 21:54 UTC, kulla commented on test/Node_test.lua
> +function TestNode:test_add()
Add `luaunit.assertIsNil(root.parent)`

2016-09-14 21:56 UTC, kulla commented on test/Node_test.lua
> +  luaunit.assertNotIs(root:find(function(node) return node:level() == 1 end), node_2)
Mach hier ein `node:level() == 2` raus (muss dann `node_2` zurückgeben)

2016-09-14 21:58 UTC, kulla requested changes
Last things which are needed before the merge...

2016-09-15 06:55 UTC, kulla commented
At the end only one function is missing:

- [ ] `Node:find_parent()`

2016-09-15 08:19 UTC, vhaller commented on test/Node_test.lua
> +  luaunit.assertNil(root.parent)
When I add this assertion, the test fails:

Failed tests:
-------------
1) Test_Node.test_new
.\test\Node_test.lua:18: Contents of the tables are not identical:
Expected:
{}
Actual:
<table: 00630460> {
    <table: 00630488> {
        children=<table: 006304B0> {},
        parent=<table: 00630438> {children=<table: 00630460>}
    },
    <table: 006304D8> {
        children=<table: 00630500> {<table: 00630528> {children=<table: 00630550> {}, parent=<table: 006304D8>}},
        parent=<table: 00630438>
    }
}
stack traceback:
        .\test\Node_test.lua:18: in function 'Test_Node.test_new'

2016-09-15 08:22 UTC, vhaller commented on test/Node_test.lua
> +function TestNode:test_add()
To TestNode:test_new() or to TestNode:test_add()?

2016-09-15 08:23 UTC, vhaller commented on test/Node_test.lua
> +function TestNode:test_add()
Isn't it there already?

2016-09-15 08:26 UTC, vhaller commented on test/Node_test.lua
> +  luaunit.assertNotIs(root:find(function(node) return node:level() == 1 end), node_2)
In Zeile 48?

2016-09-15 08:36 UTC, kulla commented on test/Node_test.lua
> +function TestNode:test_add()
`test_add` hasn't this test already... (each test case needs all assertations in order have a full coverage even if there are overlaps between tests)

2016-09-15 08:37 UTC, kulla commented on test/Node_test.lua
> +  luaunit.assertNil(root.parent)
Stimmt. Add `local root = Node:new()` at the beginning of the test...

2016-09-15 08:39 UTC, kulla commented on test/Node_test.lua
> +  luaunit.assertNotIs(root:find(function(node) return node:level() == 1 end), node_2)
ah, ne, passt hier...

2016-09-15 08:40 UTC, kulla reviewed
AW

2016-09-15 08:41 UTC, kulla commented on test/Node_test.lua
> +  luaunit.assertNotIs(root:find(function(node) return node:level() == 1 end), node_2)
Passt

2016-09-15 08:42 UTC, kulla approved these changes

2016-09-15 08:43 UTC, kulla commented on test/Node_test.lua
> +  luaunit.assertNotIs(root:find(function(node) return node:level() == 1 end), node_2)
Passt

2016-09-15 08:43 UTC, kulla requested changes

2016-09-15 08:53 UTC, vhaller commented on test/Node_test.lua
> +  luaunit.assertNil(root.parent)
Alright, thanks.

2016-09-15 08:54 UTC, vhaller commented on test/Node_test.lua
> +function TestNode:test_add()
I understand.

2016-09-15 15:19 UTC, kulla approved these changes

2016-09-15 15:19 UTC, merged